name: Deploy to main
on:
  push:
    branches:
      - main
      - master
      #here we choose to deploy only when a push is on main branch
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: https://www.arkyasmal.com
    steps:
    - uses: actions/checkout@v4
    - uses: aasmal97/deploy-static-app-to-aws@v2.0.1
      with: 
        aws_region: ${{ secrets.AWS_APP_REGION }}
        aws_access_key_id: ${{ secrets.AWS_S3_DEPLOY_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_S3_DEPLOY_SECRET_KEY }}
        cloudfront_distribution_id: ${{ secrets.AWS_APP_DISTRIBUTION_ID }}
        bucket_name: ${{ secrets.AWS_APP_BUCKET_NAME }}
        app_secrets: ${{ toJson(secrets) }}
        node_verison: 20
        path_to_app: ./
        build_dir: "./dist"
        secrets_prefix: "REACT_APP.*"